[versions]
appCompat="1.6.1"
koin="4.1.0-Beta7"
koinAnnotations="2.0.1-Beta1"

[libraries]
app-compat = {module="androidx.appcompat:appcompat", version.ref = "appCompat"}
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-annotations = {module = "io.insert-koin:koin-annotations", version.ref = "koinAnnotations"}
koin-ksp-compiler = {module = "io.insert-koin:koin-ksp-compiler", version.ref = "koinAnnotations"}